### ISSUE TITLE
WiiU controller default

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#142] opened 2022-05-08 09:22 UTC
default gamepad for cemu is Pro Controller. Toad Treasure Tracker doesnt work with the Pro controller. Maybe default should be switcht to WiiU controller?

**Comment by Godsbane** [comment] 2022-05-08 20:20
duplicate of #87

**Comment by Godsbane** [comment] 2022-05-10 06:45
I added a Gamepad based controller today with Gyro control.

Should test if it works fine even if the user does NOT have gyro.

If it works fine, we should just switch to that as the default. Then if the user adds gyro later, it should just work.

**Comment by Godsbane** [comment] 2022-05-11 20:24
reports that Shovel knight, Twilight princess (inventory needs touch), Xenoblade chronicles x (map on touchscreen)
captain toad treasure tracker among other would benefit from this.

I know of no game that does NOT work with gamepad mode.

**Closed** 2022-05-26 21:28 UTC
Labels: enhancement, Fixed in Dev
