### ISSUE TITLE
Make a storage directory

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#151] opened 2022-05-09 05:08 UTC
Make a storage directory and move / redirect all large storage folders used by emulators here.

- [x] Cemu:
$romsPath/wiiu/mlc01

- [x] rpcs3: (already moved to saves)
dev_hdd0

- [x] xemu: (already moved to saves)
xbox_hdd.qcow2

- [x] yuzu: (moved to Emulation/storage)
/home/deck/.var/org.yuzu_emu.yuzu/data/yuzu/nand
/home/deck/.var/org.yuzu_emu.yuzu/data/yuzu/sdmc

- [ ] citra:
/home/deck/.var/app/org.ctira_emu.citra/data/citra-emu/nand/
/home/deck/.var/app/org.ctira_emu.citra/data/citra-emu/sdmc/

**Comment by Godsbane** [comment] 2022-06-06 08:10
yuzu done in Dev.

**Comment by Godsbane** [comment] 2022-06-18 16:54
rpcs3, yuzu, xemu done in main

**Comment by Godsbane** [comment] 2022-06-18 16:54
Is citra worth doing?

**Comment by protoz** [comment] 2022-06-19 15:29
I was going to create a new issue, but this would be nice to have for Dolphin as the flatpak Syncthings cannot get to the symlinked directory where saves are kept for Wii and Gamecube.  Even referencing the actual directory under /home/deck/ it doesn't seem to have permission to see it even though it's running as the deck user.

I haven't tried ppsspp for saves yet to see if I will have the same issue or not, but Cemu saves work as they are in the Emulation directory instead of a directory nestled away in hidden folders.

**Comment by saildot4k** [comment] 2022-09-28 21:36
@protoz You can give syncthing permission to access ~/.var/app/appfolder/
Flatseal makes this quite easy.
I use syncthing to sync all my saves/states/memcards etc this way unless the folder was moved. Syncthing does not work with symlinks by design so I choose the source when emudeck script has moved things around.

**Comment by chabad360** [comment] 2022-10-14 04:38
I wouldn't complain if this would be done for citra, then I could easily transfer over everything that's already on my computer.

**Comment by dragoonDorise** [comment] 2022-12-10 00:42
@Godsbane  done [here](https://github.com/dragoonDorise/EmuDeck/commit/bc86c580aa1e9b012c5fa69a56fef3a8bfab99c8) We need to test it :)

**Comment by dragoonDorise** [comment] 2022-12-18 21:33
This should be fixed in 2.0.8. Please reopen this if you still find issues!

**Closed by dragoonDorise** 2022-12-18 21:33 UTC
Labels: enhancement, Fixed in Dev
