### ISSUE TITLE
streaming gaming services?

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#144] opened 2022-05-08 09:23 UTC
I know it isn't emulation really and is probably outside of the scope for the project, but possibly adding an optional setup for Chiaki's (PS4/5 remote play app) appimage (apparently the Flatpak on Discover is old) with images for Steam's UI and a controller map that includes "T" and "Escape" for the back paddles (touchpad and PS button, otherwise all controls map fine by default), and the python script for getting your PSN account ID could be helpful.

**Comment by Godsbane** [comment] 2022-05-08 20:19
duplicate of #86

**Comment by Godsbane** [comment] 2022-05-10 06:38
Ps4/5 = Chiaki
Moonline = nvidia pc
Parsec = any pc

**Comment by neoKushan** [comment] 2022-05-23 09:39
Possibly consider xcloud in here as well? It's supported on deck but the installation is a bit arduous for a new user, however it'd be fairly easy to write a script to set it up for them as it's basically install edge via discover and create a specific shortcut in steam.

**Comment by Godsbane** [comment] 2022-05-23 14:11
Sure let's add it to the list.

**Comment by KingIzzymon** [comment] 2023-01-13 20:53
@dragoonDorise & @Godsbane 

Would you guys be willing to implement a new SRM parser that could solve cloud-based launchers & links (eg XCloud, Parsec, Youtube, etc)? It works by running a shell script to launch Chrome in kiosk mode and access the associated website. The script file will be named for the SteamGridDB match (example: YouTube.sh) and then just copy and edit the "LINK" parameter in the script for the website you want access to in Game Mode.

Tested and working with:
* YouTube
* Amazon Prime
* Hulu
* Crunchyroll
* [webRcade](https://www.webrcade.com/)
* [LinuxServer's EmulatorJS](https://www.linuxserver.io/blog/self-hosted-web-based-emulation)
* Parsec

Example Script ([webRcade](https://play.webrcade.com/)):
```sh
#!/usr/bin/bash

LINK="https://play.webrcade.com/"

"/usr/bin/flatpak" run --branch=stable --arch=x86_64 --command=/app/bin/chrome --file-forwarding com.google.Chrome @@u @@ --window-size=1024,640 --force-device-scale-factor=1.25 --device-scale-factor=1.25 --kiosk "${LINK}"
```

New Parser (Cloud):
```json
[
  {
    "parserType": "Glob",
    "configTitle": "Cloud",
    "steamCategory": "${Cloud}",
    "steamDirectory": "${steamdirglobal}",
    "romDirectory": "${romsdirglobal}/cloud",
    "executableArgs": "/bin/bash \"${filePath}\"",
    "executableModifier": "\"${exePath}\"",
    "startInDirectory": "",
    "titleModifier": "${fuzzyTitle}",
    "imageProviders": ["SteamGridDB"],
    "onlineImageQueries": "${${fuzzyTitle}}",
    "imagePool": "${fuzzyTitle}",
    "defaultImage": "",
    "defaultTallImage": "",
    "defaultHeroImage": "",
    "defaultLogoImage": "",
    "defaultIcon": "/home/deck/.config/EmuDeck/backend/configs/steam-rom-manager/userData/img/default/icon.png",
    "localImages": "",
    "localTallImages": "",
    "localHeroImages": "",
    "localLogoImages": "",
    "localIcons": "",
    "userAccounts": {
      "specifiedAccounts": "",
      "skipWithMissingDataDir": true,
      "useCredentials": true
    },
    "executable": {
      "path": "",
      "shortcutPassthrough": false,
      "appendArgsToExecutable": false
    },
    "parserInputs": {
      "glob": "**/${title}@(.sh)"
    },
    "titleFromVariable": {
      "limitToGroups": "",
      "caseInsensitiveVariables": false,
      "skipFileIfVariableWasNotFound": false,
      "tryToMatchTitle": false
    },
    "fuzzyMatch": {
      "replaceDiacritics": true,
      "removeCharacters": true,
      "removeBrackets": true
    },
    "imageProviderAPIs": {
      "SteamGridDB": {
        "nsfw": false,
        "humor": false,
        "styles": [],
        "stylesHero": [],
        "stylesLogo": [],
        "stylesIcon": [],
        "imageMotionTypes": ["static"]
      }
    },
    "parserId": "",
    "version": 1
  }
]
```

**Comment by KingIzzymon** [comment] 2023-01-13 20:54
Also... itd be nice if during the next EmuDeck update, that it doesnt delete any custom parsers that users make... I've had to recreate mine.

**Comment by Godsbane** [comment] 2023-01-13 21:15
Do you have these scripts already built? 

I have built and half tested a cloud parser before, exactly like what you did actually. I tested chiaki, and Xcloud with edge and it all seemed to work out nicely.

Anyways if you want to put together a PR, I am happy to review and implement.

I can also open a feature branch for it and we can collaborate on it.

**Comment by KingIzzymon** [comment] 2023-01-13 22:03
Sure thing. I'll submit it tonight.

**Comment by KingIzzymon** [comment] 2023-01-13 22:31
@Godsbane What should I put down for the parserId and version?

**Comment by Godsbane** [comment] 2023-01-13 23:15
https://github.com/dragoonDorise/EmuDeck/tree/Add-cloud-gaming/tools/cloud

Made a feature branch off main, and a folder.

Pr to here please. I am out so I will review later :)

**Comment by KingIzzymon** [comment] 2023-01-13 23:29
Sounds good. I'm almost done but no rush :) I'm also trying to get ahold of SteamGridDB to see why they havent validated webRcade yet... I uploaded artwork about 2 months ago =/

**Comment by KingIzzymon** [comment] 2023-01-14 01:01
Hey @Godsbane , Do you know how to make the scripts executable out of the box? Or have an idea on some setup script to add something like:

```sh
cd %ROM%/cloud
chmod +x ./*
```

**Closed** 2023-04-27 05:51 UTC
Labels: enhancement, Fixed in Dev, non-emulation
