### ISSUE TITLE
RetroAchievements login not working on EmuDeck

### ISSUE THREAD

**Issue by DaniPhoFani** [dragoonDorise/EmuDeck#619] opened 2023-02-06 20:43 UTC
I keep getting a "Username/Password wrong" error message when trying to put in my RetroAchievements credentials in EmuDeck. I am 100% certain I am typing my correct credentials. My login works fine on RetroAchievements.com and when I open RetroArch in desktop mode but EmuDeck won't accept it. It was working fine two weeks ago (last time I played a game on Deck with Retro Achievements). I loaded up a rom with Retro Achievements today via parser in gaming mode to find that my RA login was gone in RetroArch.

Then I went into EmuDeck and tried re-entering username and password. Kept getting "Wrong username/password" error message.

Didn't work. Typed the same login into Retroachievements on a browser, worked fine.

Reset my username and password, tried it again on browser and Emudeck. Logged in again on browser, EmuDeck still kept spitting back "wrong username/password"

Went into desktop mode, booted up RetroArch without a game. Opened Settings -> Achievements 

Put in my username and new password, saved the config, loaded a game which then loaded my achievements fine, so my login definitely works fine on RetroArch itself.

Went into Emudeck again, tried username and password again, still got "Wrong Username/Password" error.

Dev from the discord mentioned special characters can cause problems. My password does have at least one special character in it.

**Comment by JMCee** [comment] 2023-02-12 13:45
I was just having the same issue. In the end I just changed my password to one without any special characters and the login then worked.

**Comment by Godsbane** [comment] 2023-02-13 16:35
i believe i have corrected this in the Beta of the appimage. If either of you want to test it, let me know. I'd appreciate it. it's not published yet, so i have a one off build.

**Comment by KBouder** [comment] 2023-02-27 06:28
I will chime in on this, as I used the beta login tool a few days ago, but it did not actually log me in on either Retroarch or PCSX2.

**Comment by KBouder** [comment] 2023-02-27 21:18
> as mentioned it was in a local build; not the beta. I will see about pushing the change to the main beta regardless soon.

Apologies, I misread that part.

**Comment by Godsbane** [comment] 2023-02-28 00:54
no worries - i have promoted the version with the fix to the current beta. if you relaunch it you can test it. Let me know if you still have trouble with it.

**Comment by KBouder** [comment] 2023-02-28 02:02
I launched the Beta and it downloaded the update. I went to the Retro Achievements page, reset my login, then logged in with my username and password. This did not enable achievements in Retroarch or PCSX2.

**Comment by Godsbane** [comment] 2023-02-28 04:09
You were able to log in successfully though?

**Comment by KBouder** [comment] 2023-02-28 05:52
Yes, login was successful within EmuDeck, but configuration in Retroarch and PCSX2 did not change.

**Comment by KBouder** [comment] 2023-03-05 05:58
I updated EmuDeck with the most recent beta again, and now retro achievements works as intended. Not sure what changed between the last version and this version.

**Comment by CorneliousJD** [comment] 2023-04-23 13:18
Latest normal update seems to have this issue back, I just had to reset my pass to have no special characters for now until this is fixed again.

**Comment by Godsbane** [comment] 2023-04-23 18:15
It hasn't been fixed in stable. You have to use beta.

**Closed** 2023-04-27 05:51 UTC
Labels: Fixed in Dev, AppImage Issue
