### ISSUE TITLE
Add left analog stick to mirror the d-pad controls for older systems

### ISSUE THREAD

**Issue by berpdreyfuss** [dragoonDorise/EmuDeck#213] opened 2022-05-20 10:16 UTC
I like to configure the left analog stick to act the same as the d-pad in Retro Arch for older systems that didn't have an analog stick. It is very useful for shmups, for example.

**Comment by KylerNyhagen** [comment] 2022-05-22 23:24
Can definitely be looked in to, but in the meantime you can manually change the layout and just make the stick be a D-Pad through the Steam UI!

**Comment by neoKushan** [comment] 2022-05-23 09:37
There is a simple toggle within retroarch to do this, under Controls look for "Analogue to Digital type" and set it to the Left Analogue stick. 

Would be good to set this as default on most systems that don't have an analogue stick.

**Comment by Godsbane** [comment] 2022-05-24 07:35
I looked into this. We would need to set this as the default, and then override it for certain cores. This may become a default, but not until it can be thoroughly tested to make sure it doesn't break anything.

see here for an example of a problem caused by setting this value: https://forums.libretro.com/t/how-do-i-make-the-analog-to-digital-type-core-specific/4039

**Comment by berpdreyfuss** [comment] 2022-05-24 08:08
Thank you for looking into this! I use input core remapping, which has to be set for each core, but I don't know if core overrides might be better suited.

**Comment by dragoonDorise** [comment] 2022-05-29 17:35
Note for testing:
add input_player1_analog_dpad_mode = "1" on the core override cfgs

**Comment by dragoonDorise** [comment] 2022-08-06 10:42
Fixed in 0.17.6

**Closed by dragoonDorise** 2022-08-06 10:42 UTC
Labels: enhancement, Fixed in Dev
