### ISSUE TITLE
Enabling CRT Shader 3D causes N64 and Dreamcast to have a blank screen

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [dragoonDorise/EmuDeck#473] opened 2022-10-21 16:03 UTC
When CRT Shader 3D is enabled both N64 and Dreamcast start with a blank screen. If you enter Retroarch settings and toggle the shaders while running the game it will display. Disabling the shaders entirely from Emudeck also prevents the issue from happening

**Comment by Godsbane** [comment] 2022-10-22 08:13
The root cause of this is both filter and shader on.

If you go to Emudeck-->tools->guides-->RetroArch
And then hit reset config it should fix this in general by removing the filter entries.

**Comment by TheMeanCanEHdian** [comment] 2022-10-22 13:09
What is the filter entry a result of? Was there something I did here to cause this?

**Comment by Godsbane** [comment] 2022-10-23 07:17
There was a bug immediately after launch for 2.0 for n64 CRT being toggled on, also turning the filter on. That was hotfixed in our configs though. If you reset config or go through the update process or use quick settings and you still see this issue, please let me know.

**Comment by TheMeanCanEHdian** [comment] 2022-10-24 14:12
I reset the config as suggested but now (even after toggling them off and on) neither the widescreeen aspect ratio or shaders apears to be applying. I followed that by running through a cusom setup again where (I selected both widescreen and shaders) and it broke with the same results as before.

**Comment by Godsbane** [comment] 2022-10-26 04:56
It also appears to be an issue with widescreen and shaders, as you mentioned. Hotfixing it so that when widescreen is selected, it will overrule the shader selection for n64 and dreamcast.

**Comment by TheMeanCanEHdian** [comment] 2022-10-26 13:51
Just to confirm, this is not live yet for testing?

**Comment by Godsbane** [comment] 2022-10-26 17:04
It should be working now in live. I didn't close it yet though.

**Comment by Godsbane** [comment] 2022-10-28 16:51
Can you upload the emudeck log again please

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 18:10
Sure thing, here you are: [emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/9890852/emudeck.log)

**Comment by Godsbane** [comment] 2022-10-28 18:36
may i also ask for  `/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config/Mupen64Plus-Next/n64.cfg` please?

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 18:40
No problem, had to put it in a zip.
[n64.zip](https://github.com/dragoonDorise/EmuDeck/files/9890992/n64.zip)

**Comment by Godsbane** [comment] 2022-10-28 18:51
you have a black screen with this? shader isn't on.

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 18:53
Ah sorry, I forgot to flip it back to be broke. I will do so and re-upload both files.

**Comment by Godsbane** [comment] 2022-10-28 18:55
You had me questioning my sanity lol

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 19:08
This should be with the shaders on as well.
[log&config.zip](https://github.com/dragoonDorise/EmuDeck/files/9891126/log.config.zip)

**Comment by Godsbane** [comment] 2022-10-28 19:15
Thanks - i'm still questioning my sanity - as every single entry in the log with regards to n64 shaders is "false" and yet your files says true. Did you use the quick settings after using the custom install?

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 19:17
I did, do you want me to do a new custom install with shaders and widescreen on and provide the files again?

**Comment by Godsbane** [comment] 2022-10-28 19:36
nope - just as long as i know the exact steps :)

custom install - wide on, shaders off -- > quick settings 3d shaders on?

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 19:36
Yep, to the best of my recollection that is what I did.

**Comment by Godsbane** [comment] 2022-10-28 19:37
thanks! will look into some UI adjustments here. I appreciate your efforts.

**Comment by TheMeanCanEHdian** [comment] 2022-10-28 19:39
Happy to help.

**Comment by Jimbles98** [comment] 2022-10-31 23:55
This is still happening on N64 for me. (Dreamcast works fine)
I've tried resetting the configs and then running through custom update but the issue still persists on N64.

Here are my Quick Settings:
Bezels - On
3D Aspect Ratio - 4:3
CRT Shader 3D - On
Sega Aspect Ratio - 4:3
Dolphin Aspect Ratio - 4:3
LCD Shader Handhelds - On
NES and SNES Aspect Ratio - 8:7
CRT Shader 2D - On

Log FIle: http://sprunge.us/Jy2B2Z

**Closed** 2023-04-27 05:51 UTC
Labels: Fixed in Dev
