### ISSUE TITLE
EmuDeck 2.0 installer cannot see my SD card

### ISSUE THREAD

**Issue by JediRhymeTrix** [dragoonDorise/EmuDeck#439] opened 2022-10-16 18:50 UTC
The SD card is properly mounted and is visible in both desktop mode and Game mode and the old installation of EmuDeck used the SD card just fine. However, while trying to update to v2, the installer only shows Internal Storage and Custom Directory options.

**Comment by JediRhymeTrix** [comment] 2022-10-16 18:53
Update: went back and forth from the location selection screen after closing and re-opening installer a few times and it could finally see the SD card.

**Comment by Godsbane** [comment] 2022-10-17 05:17
yes going back and forth should load them. This is a duplicate of #437 so closing it and going to use that one to track the issue.

**Closed by Godsbane** 2022-10-17 05:17 UTC
