### ISSUE TITLE
Unable to uninstall as it does not progress

### ISSUE THREAD

**Issue by KoiV1224** [dragoonDorise/EmuDeck#487] opened 2022-10-29 01:41 UTC
EmuDeck does not uninstall by clicking the desktop icon to do so. 

SRM Version: 2.3.40
Linux version: Linux 5.13

Steps to recreate:
1. Click / Press "Uninstall EmuDeck" on desktop
2. Click "Nope, I want to uninstall EmuDeck"
3. Click "Continue"
4. Do not select any emulators to keep, just click "OK"

Issue that occurs:
After repeating the steps, Konsole opens up and displays

`1.                        org.libretro.RetroArch stable r`
`Uninstalling...`

and displays a single white box which I believe is the progress bar and do not go any further.

Ways I have tried to fix:

- Restarting SteamDeck
- Exiting Steam
- Reopening Steam
- Retrying to uninstall
- Looked through Steam ROM Manager to try and find something that can help
- Looked through FAQs, Discord, Github, and Google

**Comment by Godsbane** [comment] 2022-10-29 07:50
Hi koiv - i installed emudeck and then i uninstalled emudeck, and it seems to have progressed without a problem. There's a log created on your desktop during uninstall.

if it got stuck uninstall retroarch - could you test the same thing from discover please? Open it up and find and uninstall it. See if you get a discover error.

**Comment by Godsbane** [comment] 2022-11-09 05:49
I'm closing this as i could not reproduce it, and never got a response.

**Closed by Godsbane** 2022-11-09 05:49 UTC
