### ISSUE TITLE
Enabling hardcore mode for RetroAchievements doesn't work

### ISSUE THREAD

**Issue by sybenx** [dragoonDorise/EmuDeck#476] opened 2022-10-22 00:29 UTC
Setting it on in EmuDeck, it's off in retroarch settings. Further made confusing because enabling it in retroarch didn't work by default because save configuration on retroarch exit is turned off.

It should be explained by the EmuDeck hardcore mode toggle: No save states, but double points

**Comment by Godsbane** [comment] 2022-10-22 00:59
Can you attach your ~/emudeck/emudeck.log please

**Comment by sybenx** [comment] 2022-10-22 01:08
[emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/9843214/emudeck.log)

**Comment by Godsbane** [comment] 2022-10-22 01:59
Thanks for providing that. I can't reproduce the reported behavior. 

Here's the data from your log:

> The flag was set to  **achievementsHardcore=false**

and it did:

> Updating: /home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg - cheevos_enable =  to cheevos_enable = "true"
> Updating: /home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg - cheevos_hardcore_mode_enable =  to cheevos_hardcore_mode_enable = "false"


I've just tested this on my own deck and it worked as expected. I enabled the toggle and it turned green. Then when the script ran it did the following:

> the flag was set to **achievementsHardcore=true**

and it did:

> Updating: /home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg - cheevos_enable =  to cheevos_enable = "true"
> Updating: /home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg - cheevos_hardcore_mode_enable =  to cheevos_hardcore_mode_enable = "true"


Can you try again and make sure you toggled it to green and then continue?

What I DID notice in playing around - was that going back to the RetroAchievements screen toggled it off by default.

**Comment by sybenx** [comment] 2022-10-22 03:10
[emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/9843455/emudeck.log)
I double checked it was toggled on. Did not work

**Comment by Godsbane** [comment] 2022-10-22 03:34
that's a stubborn toggle. again it wrote out achievementsHardcore=false in your log.

@dragoonDorise I need you to look at this, and request other logs or files for debugging.

**Comment by dragoonDorise** [comment] 2022-12-10 00:09
I've tested this issue, the way the Appimage works it's "impossible" to get the switch checked but then have the option set to false as the switch visual status reacts to the option every time is set as true or false, not the other way around.

@sybenx did you manage to activate hardcore mode?

**Comment by ybbuc** [comment] 2023-03-26 03:19
I'm having this issue. Any updates?

**Comment by dragoonDorise** [comment] 2023-03-30 18:20
@ybbuc this is working fine on the current beta, it will be fixed on the next release :)

**Closed** 2023-04-27 05:51 UTC
Labels: Fixed in Dev
