### ISSUE TITLE
.gdi and .iso are left behind while .bin & .cue are being removed three times

### ISSUE THREAD

**Issue by eur0pa** [dragoonDorise/EmuDeck#107] opened 2022-05-03 21:52 UTC
https://github.com/dragoonDorise/EmuDeck/blob/0636b0eea249177eb863489e38b10e880f55c87c/tools/chdconv/chddeck.sh#L38#L39

The `rm` operation should be done on .gdi and .iso respectively instead of .cue and .bin. Guess that was a hasty copy-paste : )

On another note, I'm not an expert on the NKit format many GC ISOs come in, and whether converting a nkit.iso image into nkit.chd would raise issues. Don't think it should but it'd be better to check.

Nice work overall, the project makes everything smoother and more enjoyable

**Comment by Godsbane** [comment] 2022-05-03 22:06
Duplicate of #103

**Comment by Godsbane** [comment] 2022-05-03 22:08
Good point about the nkit iso's.

**Closed** 2022-05-08 02:44 UTC
Labels: duplicate, Fixed in Dev
