### ISSUE TITLE
Expert Mode: Only install RetroArch cores if RetroArch is installed

### ISSUE THREAD

**Issue by ajburley** [dragoonDorise/EmuDeck#389] opened 2022-09-12 21:52 UTC
I installed in expert mode and only selected PCSX2-Qt, Dolphin and Cemu, but EmuDeck also downloaded all the RetroArch cores which is a pointless waste of space as RetroArch is not even installed.

**Comment by Godsbane** [comment] 2022-09-13 00:49
Can you attach your log please?

**Comment by ajburley** [comment] 2022-09-13 08:30
In my case I think it's emudeck.last.log because I tried to run it again after that briefly to see if I could fix it. Attached the log.
[emudeck.last.log](https://github.com/dragoonDorise/EmuDeck/files/9554910/emudeck.last.log)

**Comment by Godsbane** [comment] 2022-09-13 14:56
Hiya,

Went through the log. You told it to only install the three you mentioned, but you also left all the reconfigure on for the other emulators, which is why it did just that.

```
Expert mode begin
user selected: SteamGyro|updateSRM|selectEmulators|selectEmulatorConfig|selectWideScreen
Emu Install selected: PCSX2-QT|Dolphin|Cemu  < -- looks good, exactly as you intended
echo "Emulators to reinstall selected: $emusToReset"  < -- this is just to show the bug in the text. Will correct the log to say reconfigure not reinstall.
Emulators to reinstall selected: RetroArch|MAME|PrimeHack|PCSX2-Legacy|PCSX2-QT|RPCS3|Citra|Dolphin|Duckstation|PPSSPP|Yuzu|Ryujinx|Cemu|Xemu|Steam Rom Manager|EmulationStation DE
```

So because it was set to reconfigure these, it did. Part of the configure step of RetroArch is the core download.

All you need to do is delete the folder if you do not want it. ~/.var/app/org.libretro.RetroArch

hope this all helps understand why what happened, happened :)

**Comment by ajburley** [comment] 2022-09-13 16:39
Yes it does :) - although as a user new to the tool, I assumed that the "reset config" stuff would only be applied for those emulators I had selected to install in the earlier step... I did notice that all of them were ticked, but I thought probably I don't need to go through and untick the ones I don't need (which was a lot) because I thought it will happen automatically.

Could this perhaps be converted to a feature request to only display the emulators you are trying to install in the "reset config" dialog?

**Comment by Godsbane** [comment] 2022-09-14 05:34
The problem is, it's 100% valid to reset the config only (or do any combination of these things). Sometimes a user may have screwed something up and wants to just do that step.

The next release will clean this UI up a lot and make it much more user friendly. I'll close this for now, but next release if you still think things are weird, please let us know.

**Closed by Godsbane** 2022-09-14 05:34 UTC
